import libs  = mini_chromium%lib{mini_chromium}
import libs += libcrashpad%lib{crashpad_build}
import libs += libcrashpad%lib{crashpad_util}
import libs += libcrashpad%lib{crashpad_net}
import libs += libcrashpad%lib{crashpad_client_common}
import libs += libcrashpad%lib{crashpad_snapshot}
import libs += libcrashpad%lib{crashpad_handler}
import libs += libcrashpad%lib{crashpad_compat}
import libs += libcrashpad%lib{crashpad_tool_support}
if ($cxx.target.class == 'linux')
{
  import libs += libcrashpad%lib{crashpad_pthread_create}
}

crashpad_handler_exe = ($cxx.target.class == 'windows' ? crashpad_handler.exe : crashpad_handler)
crash_handler_com = crash_handler.com

./: exe{$crashpad_handler_exe}
./: exe{$crash_handler_com}: include = ($cxx.target.class == 'windows')

exe{$crashpad_handler_exe}: {cxx}{main} $libs
exe{$crash_handler_com}: {cxx}{main} $libs: include = ($cxx.target.class == 'windows')

if ($cxx.target.system == 'win32-msvc')
{
  exe{$crashpad_handler_exe}: cxx.loptions += '/subsystem:windows'
  exe{$crash_handler_com}: cxx.loptions += '/subsystem:console'
}
