import intf_libs = mini_chromium%lib{mini_chromium}

include ../client/
include ../compat/
include ../minidump/
include ../util/
include ../build/

intf_libs += ../build/lib{crashpad_build}

impl_libs  = ../util/lib{crashpad_util}

snapshot_impl_libs  = ../client/lib{crashpad_client_common}
snapshot_impl_libs += ../compat/lib{crashpad_compat}
snapshot_impl_libs += ../minidump/lib{crashpad_format}
snapshot_impl_libs += ../util/lib{crashpad_util}

context_common_headers  = cpu_architecture \
                          cpu_context

context_common_source   = cpu_context

#TODO Figure out what mac_universal is?, x86/cpuid_reader should only be included for mac_universal...

snapshot_common_headers = annotation_snapshot \
                          capture_memory \
                          crashpad_info_client_options \
                          exception_snapshot \
                          handle_snapshot \
                          memory_snapshot \
                          memory_snapshot_generic \
                          minidump/exception_snapshot_minidump \
                          minidump/memory_snapshot_minidump \
                          minidump/minidump_annotation_reader \
                          minidump/minidump_context_converter \
                          minidump/minidump_simple_string_dictionary_reader \
                          minidump/minidump_stream \
                          minidump/minidump_string_list_reader \
                          minidump/minidump_string_reader \
                          minidump/module_snapshot_minidump \
                          minidump/process_snapshot_minidump \
                          minidump/system_snapshot_minidump \
                          minidump/thread_snapshot_minidump \
                          module_snapshot \
                          process_snapshot \
                          snapshot_constants \
                          system_snapshot \
                          thread_snapshot \
                          unloaded_module_snapshot \
                          x86/cpuid_reader \
                          memory_map_region_snapshot

snapshot_common_source  = annotation_snapshot \
                          capture_memory \
                          crashpad_info_client_options \
                          handle_snapshot \
                          memory_snapshot \
                          minidump/exception_snapshot_minidump \
                          minidump/memory_snapshot_minidump \
                          minidump/minidump_annotation_reader \
                          minidump/minidump_context_converter \
                          minidump/minidump_simple_string_dictionary_reader \
                          minidump/minidump_string_list_reader \
                          minidump/minidump_string_reader \
                          minidump/module_snapshot_minidump \
                          minidump/process_snapshot_minidump \
                          minidump/system_snapshot_minidump \
                          minidump/thread_snapshot_minidump \
                          unloaded_module_snapshot \
                          x86/cpuid_reader

snapshot_posix_headers  = posix/timezone

snapshot_posix_source   = posix/timezone

snapshot_macos_headers  = mac/cpu_context_mac \
                          mac/exception_snapshot_mac \
                          mac/mach_o_image_annotations_reader \
                          mac/mach_o_image_reader \
                          mac/mach_o_image_segment_reader \
                          mac/mach_o_image_symbol_table_reader \
                          mac/module_snapshot_mac \
                          mac/process_reader_mac \
                          mac/process_snapshot_mac \
                          mac/process_types \
                          mac/process_types/flavors \
                          mac/process_types/internal \
                          mac/process_types/traits \
                          mac/system_snapshot_mac \
                          mac/thread_snapshot_mac \
                          mac/process_types/flavors \
                          mac/process_types/internal \
                          mac/process_types/traits

snapshot_macos_source   = mac/cpu_context_mac \
                          mac/exception_snapshot_mac \
                          mac/mach_o_image_annotations_reader \
                          mac/mach_o_image_reader \
                          mac/mach_o_image_segment_reader \
                          mac/mach_o_image_symbol_table_reader \
                          mac/module_snapshot_mac \
                          mac/process_reader_mac \
                          mac/process_snapshot_mac \
                          mac/process_types \
                          mac/process_types/custom \
                          mac/system_snapshot_mac \
                          mac/thread_snapshot_mac \
                          mac/process_types/custom

define proctype: file
proctype{*}: extension = proctype
snapshot_macos_files =    mac/process_types/all \
                          mac/process_types/annotation \
                          mac/process_types/crashpad_info \
                          mac/process_types/crashreporterclient \
                          mac/process_types/dyld_images \
                          mac/process_types/loader \
                          mac/process_types/nlist

snapshot_linux_headers  = linux/capture_memory_delegate_linux \
                          linux/cpu_context_linux \
                          linux/debug_rendezvous \
                          linux/exception_snapshot_linux \
                          linux/process_reader_linux \
                          linux/process_snapshot_linux \
                          linux/signal_context \
                          linux/system_snapshot_linux \
                          linux/thread_snapshot_linux \
                          sanitized/memory_snapshot_sanitized \
                          sanitized/module_snapshot_sanitized \
                          sanitized/process_snapshot_sanitized \
                          sanitized/sanitization_information \
                          sanitized/thread_snapshot_sanitized \
                          crashpad_types/crashpad_info_reader \
                          crashpad_types/image_annotation_reader \
                          elf/elf_dynamic_array_reader \
                          elf/elf_image_reader \
                          elf/elf_symbol_table_reader \
                          elf/module_snapshot_elf

snapshot_linux_source  = linux/capture_memory_delegate_linux \
                         linux/cpu_context_linux \
                         linux/debug_rendezvous \
                         linux/exception_snapshot_linux \
                         linux/process_reader_linux \
                         linux/process_snapshot_linux \
                         linux/system_snapshot_linux \
                         linux/thread_snapshot_linux \
                         sanitized/memory_snapshot_sanitized \
                         sanitized/module_snapshot_sanitized \
                         sanitized/process_snapshot_sanitized \
                         sanitized/sanitization_information \
                         sanitized/thread_snapshot_sanitized \
                         crashpad_types/crashpad_info_reader \
                         crashpad_types/image_annotation_reader \
                         elf/elf_dynamic_array_reader \
                         elf/elf_image_reader \
                         elf/elf_symbol_table_reader \
                         elf/module_snapshot_elf

snapshot_win_headers   = win/capture_memory_delegate_win \
                         win/cpu_context_win \
                         win/exception_snapshot_win \
                         win/memory_map_region_snapshot_win \
                         win/module_snapshot_win \
                         win/pe_image_annotations_reader \
                         win/pe_image_reader \
                         win/pe_image_resource_reader \
                         win/process_reader_win \
                         win/process_snapshot_win \
                         win/process_subrange_reader \
                         win/system_snapshot_win \
                         win/thread_snapshot_win \
                         crashpad_types/crashpad_info_reader

snapshot_win_source    = win/capture_memory_delegate_win \
                         win/cpu_context_win \
                         win/exception_snapshot_win \
                         win/memory_map_region_snapshot_win \
                         win/module_snapshot_win \
                         win/pe_image_annotations_reader \
                         win/pe_image_reader \
                         win/pe_image_resource_reader \
                         win/process_reader_win \
                         win/process_snapshot_win \
                         win/process_subrange_reader \
                         win/system_snapshot_win \
                         win/thread_snapshot_win \
                         crashpad_types/crashpad_info_reader

./: lib{crashpad_snapshot crashpad_context}

lib{crashpad_context}: {hxx}{$context_common_headers} {cxx}{$context_common_source} $impl_libs $intf_libs

lib{crashpad_snapshot}: {hxx}{$snapshot_common_headers} {cxx}{$snapshot_common_source}
lib{crashpad_snapshot}: {hxx}{$snapshot_posix_headers} {cxx}{$snapshot_posix_source}: include = ($cxx.target.class != 'windows')
lib{crashpad_snapshot}: {hxx}{$snapshot_macos_headers} {cxx}{$snapshot_macos_source} {proctype}{$snapshot_macos_files}: include = ($cxx.target.class == 'macos')
lib{crashpad_snapshot}: {hxx}{$snapshot_linux_headers} {cxx}{$snapshot_linux_source}: include = ($cxx.target.class == 'linux')
lib{crashpad_snapshot}: {hxx}{$snapshot_win_headers} {cxx}{$snapshot_win_source}: include = ($cxx.target.class == 'windows')
lib{crashpad_snapshot}: lib{crashpad_context} $impl_libs $snapshot_impl_libs $intf_libs

# Build options.
cxx.poptions =+ "-I$src_root"/libcrashpad

switch $cxx.target.class
{
  case 'windows'
  {
    #TODO Check if powrprof.lib is required to be specifed here.
    if ($cxx.target.system != 'mingw32')
    {
      cxx.libs += powrprof.lib Advapi32.lib
    }
  }
}

# context export options.
#
lib{crashpad_context}:
{
  cxx.export.poptions = "-I$src_root"/libcrashpad
  cxx.export.libs = $intf_libs
}

# snapshot export options.
#
lib{crashpad_snapshot}:
{
  cxx.export.poptions = "-I$src_root"/libcrashpad
  cxx.export.libs = lib{crashpad_context} $intf_libs $snapshot_intf_libs
}

# Install into the crashpad/snapshot/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx proctype}{*}:
{
  install         = include/crashpad/snapshot/
  install.subdirs = true
}

lib{crashpad_context \
    crashpad_snapshot}: cxx.pkgconfig.include = include/crashpad/
