import libs += gtest%lib{gtest}
import libs += gmock%lib{gmock}
import libs += mini_chromium%lib{mini_chromium}
import libs += crashpad%lib{client}
import libs += crashpad%lib{compat}
import libs += crashpad%lib{util}
import libs += crashpad%lib{snapshot}
import libs += crashpad%lib{context}

include ../test/
libs += ../test/lib{test}

common_source =  annotation_list_test \
                 annotation_test \
                 crash_report_database_test \
                 prune_crash_reports_test \
                 settings_test \
                 simple_address_range_bag_test \
                 simple_string_dictionary_test

linux_source =   crashpad_client_linux_test

macos_source =   simulate_crash_mac_test

win_source =     crashpad_client_win_test

./: exe{crashpad_client_test}

exe{crashpad_client_test}: {cxx}{$common_source}
exe{crashpad_client_test}: {cxx}{$linux_source}: include = ($cxx.target.class == 'linux')
exe{crashpad_client_test}: {cxx}{$macos_source}: include = ($cxx.target.class == 'macos')
exe{crashpad_client_test}: {cxx}{$win_source}: include = ($cxx.target.class == 'windows')
exe{crashpad_client_test}: {cxx}{../test/gtest_main}
exe{crashpad_client_test}: $libs
exe{crashpad_client_test}: test = true

cxx.poptions += -DCRASHPAD_TEST_LAUNCHER_GOOGLETEST

# TODO Add crash handler as data dependency for CrashpadClient tests to work.
exe{crashpad_client_test}: test.options = "--gtest_filter=-\
CrashpadClient*:\
*StartHandlerInChild*"
