import intf_libs += mini_chromium%lib{mini_chromium}
import intf_libs += libz%lib{z}
if ($cxx.target.class == 'linux')
    import intf_libs += libcurl%lib{curl}

include ../compat/
include ../build/
intf_libs += ../compat/lib{crashpad_compat}
intf_libs += ../build/lib{crashpad_build}

import no_cfi_icall_intf_libs += mini_chromium%lib{mini_chromium}

util_common_headers = file/delimited_file_reader \
                      file/directory_reader \
                      file/file_helper \
                      file/file_io \
                      file/file_reader \
                      file/file_seeker \
                      file/file_writer \
                      file/filesystem \
                      file/output_stream_file_writer \
                      file/scoped_remove_file \
                      file/string_file \
                      misc/address_sanitizer \
                      misc/address_types \
                      misc/arraysize \
                      misc/as_underlying_type \
                      misc/capture_context \
                      misc/clock \
                      misc/elf_note_types \
                      misc/from_pointer_cast \
                      misc/implicit_cast \
                      misc/initialization_state \
                      misc/initialization_state_dcheck \
                      misc/lexing \
                      misc/memory_sanitizer \
                      misc/metrics \
                      misc/paths \
                      misc/pdb_structures \
                      misc/random_string \
                      misc/range_set \
                      misc/reinterpret_bytes \
                      misc/scoped_forbid_return \
                      misc/symbolic_constants_common \
                      misc/time \
                      misc/tri_state \
                      misc/uuid \
                      misc/zlib \
                      numeric/checked_address_range \
                      numeric/checked_range \
                      numeric/checked_vm_address_range \
                      numeric/in_range_cast \
                      numeric/int128 \
                      numeric/safe_assignment \
                      process/process_id \
                      process/process_memory \
                      process/process_memory_native \
                      process/process_memory_range \
                      stdlib/aligned_allocator \
                      stdlib/map_insert \
                      stdlib/objc \
                      stdlib/string_number_conversion \
                      stdlib/strlcpy \
                      stdlib/strnlen \
                      stdlib/thread_safe_vector \
                      stream/base94_output_stream \
                      stream/file_encoder \
                      stream/file_output_stream \
                      stream/log_output_stream \
                      stream/output_stream_interface \
                      stream/zlib_output_stream \
                      string/split_string \
                      synchronization/semaphore \
                      thread/stoppable \
                      thread/thread \
                      thread/thread_log_messages \
                      thread/worker_thread \
                      ../third_party/zlib/zlib_crashpad
                 
util_common_source =  file/delimited_file_reader \
                      file/file_helper \
                      file/file_io \
                      file/file_reader \
                      file/file_seeker \
                      file/file_writer \
                      file/output_stream_file_writer \
                      file/scoped_remove_file \
                      file/string_file \
                      misc/initialization_state_dcheck \
                      misc/lexing \
                      misc/metrics \
                      misc/pdb_structures \
                      misc/random_string \
                      misc/range_set \
                      misc/reinterpret_bytes \
                      misc/scoped_forbid_return \
                      misc/time \
                      misc/uuid \
                      misc/zlib \
                      numeric/checked_address_range \
                      process/process_memory \
                      process/process_memory_range \
                      stdlib/aligned_allocator \
                      stdlib/string_number_conversion \
                      stdlib/strlcpy \
                      stdlib/strnlen \
                      stream/base94_output_stream \
                      stream/file_encoder \
                      stream/file_output_stream \
                      stream/log_output_stream \
                      stream/zlib_output_stream \
                      string/split_string \
                      thread/thread \
                      thread/thread_log_messages \
                      thread/worker_thread

util_posix_headers =  posix/close_stdio \
                      posix/scoped_dir \
                      posix/scoped_mmap \
                      posix/signals \
                      posix/close_multiple \
                      posix/drop_privileges \
                      posix/process_info \
                      posix/spawn_subprocess \
                      posix/symbolic_constants_posix \
                      ../third_party/lss/lss \
                      ../third_party/lss/linux_syscall_support

util_posix_source =   file/directory_reader_posix \
                      file/file_io_posix \
                      file/filesystem_posix \
                      misc/clock_posix \
                      posix/close_stdio \
                      posix/scoped_dir \
                      posix/scoped_mmap \
                      posix/signals \
                      synchronization/semaphore_posix \
                      thread/thread_posix \
                      posix/close_multiple \
                      posix/drop_privileges \
                      posix/spawn_subprocess \
                      posix/symbolic_constants_posix

util_linux_headers =  linux/address_types \
                      linux/auxiliary_vector \
                      linux/checked_linux_address_range \
                      linux/direct_ptrace_connection \
                      linux/exception_handler_client \
                      linux/exception_handler_protocol \
                      linux/exception_information \
                      linux/memory_map \
                      linux/proc_stat_reader \
                      linux/proc_task_reader \
                      linux/ptrace_broker \
                      linux/ptrace_client \
                      linux/ptrace_connection \
                      linux/ptracer \
                      linux/scoped_pr_set_dumpable \
                      linux/scoped_pr_set_ptracer \
                      linux/scoped_ptrace_attach \
                      linux/socket \
                      linux/thread_info \
                      linux/traits \
                      process/process_memory_linux \
                      process/process_memory_sanitized

util_linux_source =   linux/auxiliary_vector \
                      linux/direct_ptrace_connection \
                      linux/exception_handler_client \
                      linux/exception_handler_protocol \
                      linux/memory_map \
                      linux/proc_stat_reader \
                      linux/proc_task_reader \
                      linux/ptrace_broker \
                      linux/ptrace_client \
                      linux/ptracer \
                      linux/scoped_pr_set_dumpable \
                      linux/scoped_pr_set_ptracer \
                      linux/scoped_ptrace_attach \
                      linux/socket \
                      linux/thread_info \
                      misc/paths_linux \
                      misc/time_linux \
                      posix/process_info_linux \
                      process/process_memory_linux \
                      process/process_memory_sanitized

util_mac_headers =    mac/xattr \
                      mach/composite_mach_message_server \
                      mach/exc_client_variants \
                      mach/exc_server_variants \
                      mach/exception_behaviors \
                      mach/exception_ports \
                      mach/mach_extensions \
                      mach/mach_message \
                      mach/mach_message_server \
                      mach/symbolic_constants_mach \
                      mac/checked_mach_address_range \
                      mac/launchd \
                      mac/mac_util \
                      mac/service_management \
                      mac/sysctl \
                      mach/bootstrap \
                      mach/child_port_handshake \
                      mach/child_port_server \
                      mach/child_port_types \
                      mach/exception_types \
                      mach/notify_server \
                      mach/scoped_task_suspend \
                      mach/task_for_pid \
                      process/process_memory_mac

util_mac_source =     mac/xattr \
                      mach/composite_mach_message_server \
                      mach/exc_client_variants \
                      mach/exc_server_variants \
                      mach/exception_behaviors \
                      mach/exception_ports \
                      mach/mach_extensions \
                      mach/mach_message \
                      mach/mach_message_server \
                      mach/symbolic_constants_mach \
                      misc/clock_mac \
                      misc/paths_mac \
                      synchronization/semaphore_mac \
                      mac/mac_util \
                      mac/service_management \
                      mac/sysctl \
                      mach/bootstrap \
                      mach/child_port_handshake \
                      mach/child_port_server \
                      mach/exception_types \
                      mach/notify_server \
                      mach/scoped_task_suspend \
                      mach/task_for_pid \
                      posix/process_info_mac \
                      process/process_memory_mac

util_macos_mm =       mac/launchd

util_win_headers =    process/process_memory_win \
                      win/address_types \
                      win/checked_win_address_range \
                      win/command_line \
                      win/context_wrappers \
                      win/critical_section_with_debug_info \
                      win/exception_codes \
                      win/exception_handler_server \
                      win/get_function \
                      win/get_module_information \
                      win/handle \
                      win/initial_client_data \
                      win/loader_lock \
                      win/module_version \
                      win/nt_internals \
                      win/ntstatus_logging \
                      win/process_info \
                      win/process_structs \
                      win/registration_protocol_win \
                      win/registration_protocol_win_structs \
                      win/safe_terminate_process \
                      win/scoped_handle \
                      win/scoped_local_alloc \
                      win/scoped_process_suspend \
                      win/scoped_registry_key \
                      win/scoped_set_event \
                      win/session_end_watcher \
                      win/termination_codes \
                      win/traits \
                      win/xp_compat

util_win_source =     file/directory_reader_win \
                      file/file_io_win \
                      file/filesystem_win \
                      misc/clock_win \
                      misc/paths_win \
                      misc/time_win \
                      process/process_memory_win \
                      synchronization/semaphore_win \
                      thread/thread_win \
                      win/command_line \
                      win/critical_section_with_debug_info \
                      win/exception_handler_server \
                      win/get_function \
                      win/get_module_information \
                      win/handle \
                      win/initial_client_data \
                      win/loader_lock \
                      win/module_version \
                      win/nt_internals \
                      win/ntstatus_logging \
                      win/process_info \
                      win/registration_protocol_win \
                      win/scoped_handle \
                      win/scoped_local_alloc \
                      win/scoped_process_suspend \
                      win/scoped_set_event \
                      win/session_end_watcher

net_common_headers =  net/http_body \
                      net/http_body_gzip \
                      net/http_headers \
                      net/http_multipart_builder \
                      net/http_transport \
                      net/url \
                      ../package

net_common_source =   net/http_body \
                      net/http_body_gzip \
                      net/http_multipart_builder \
                      net/http_transport \
                      net/url

net_macos_mm =        net/http_transport_mac
# See https://github.com/chromium/crashpad/blob/ca3cf2f4e3b5df79182888711b01bf58c1142f28/util/net/tls.gni#L20-L21
net_linux_source =    net/http_transport_libcurl

net_win_source =      net/http_transport_win

./: lib{crashpad_util} lib{crashpad_net} lib{crashpad_no_cfi_icall}

lib{crashpad_util}: {hxx}{$util_common_headers} {cxx}{$util_common_source}
lib{crashpad_util}: {hxx}{$util_posix_headers} {cxx}{$util_posix_source}: include = ($cxx.target.class != 'windows')
lib{crashpad_util}: {hxx}{$util_linux_headers} {cxx}{$util_linux_source}: include = ($cxx.target.class == 'linux')
lib{crashpad_util}: {hxx}{$util_mac_headers} {cxx}{$util_mac_source}: include = ($cxx.target.class == 'macos')
lib{crashpad_util}: {hxx}{$util_win_headers} {cxx}{$util_win_source}: include = ($cxx.target.class == 'windows')
lib{crashpad_util}: $impl_libs $intf_libs lib{crashpad_no_cfi_icall}

lib{crashpad_net}: {hxx}{$net_common_headers} {cxx}{$net_common_source}
lib{crashpad_net}: {cxx}{$net_win_source}: include = ($cxx.target.class == 'windows')
lib{crashpad_net}: {cxx}{$net_linux_source}: include = ($cxx.target.class == 'linux')
lib{crashpad_net}: $impl_libs $intf_libs lib{crashpad_util}

lib{crashpad_no_cfi_icall}: {hxx}{misc/no_cfi_icall}
lib{crashpad_no_cfi_icall}: $no_cfi_icall_intf_libs

# Build options.
cxx.poptions =+ "-I$src_root"/libcrashpad "-I$out_root"/libcrashpad -DCRASHPAD_ZLIB_SOURCE_SYSTEM -DCRASHPAD_LSS_SOURCE_EXTERNAL -DZLIB_CONST

if ($cxx.id == 'gcc')
{
    cxx.coptions += -fpermissive -Wno-multichar
}

# util export options.
lib{crashpad_util}:
{
  cxx.export.poptions = "-I$src_root"/libcrashpad "-I$out_root"/libcrashpad -DCRASHPAD_ZLIB_SOURCE_SYSTEM -DCRASHPAD_LSS_SOURCE_EXTERNAL -DZLIB_CONST
  cxx.export.libs = $intf_libs lib{crashpad_no_cfi_icall}
}

# net export options.
lib{crashpad_net}:
{
  cxx.export.poptions = "-I$src_root"/libcrashpad
  cxx.export.libs = $intf_libs
}

# no_cfi_icall export options.
lib{crashpad_no_cfi_icall}:
{
  cxx.export.poptions = "-I$src_root"/libcrashpad
  cxx.export.libs = $no_cfi_icall_intf_libs
}

switch $cxx.target.class
{
  case 'linux'
  {
    cxx.libs += -ldl
  }
  case 'macos'
  {
    cxx.libs += -framework CoreFoundation      \
                -framework Foundation          \
                -framework IOKit               \
                -framework CoreServices        \
                -lbsm
  }
  case 'windows'
  {
    #TODO Check if user32.lib are not automatically and are required to be specifed here.
    if ($cxx.target.system != 'mingw32')
    {
      cxx.libs += version.lib Advapi32.lib winhttp.lib
    }
  }
}

enable_assembly = (($cxx.target.class == 'macos') || ($cxx.target.class == 'linux'))
if ($enable_assembly)
{
    lib{crashpad_util}: cxx.coptions += "-mbmi"
}

switch $cxx.target.class
{
  case 'linux'
    assembly_source = misc/capture_context_linux.S misc/arm64_pac_bti.S
  case 'macos'
    assembly_source = misc/capture_context_mac.S
  case 'windows'
    assembly_source_win = misc/capture_context_win.asm win/safe_terminate_process.asm
}

for f: $assembly_source
{
    misc/obja{$name($f)...a.o} misc/objs{$name($f)...so.o}: $f
    {{
        diag as $>
        $cxx.path -o $path($>) -c $path($<[0]) "-I$src_root"/libcrashpad
    }}

    lib{crashpad_util}: file{$f} misc/obj{$name($f)}
}

for f: $assembly_source_win
{
    ml = $directory($effect($cxx.path))/ml64.exe

    obja{$name($f)...a.obj} objs{$name($f)...s.obj}: $f $ml
    {{
        diag masm64 $>
        $ml /Fo $path($>) /c $path($<[0])
    }}

    lib{crashpad_util}: file{$f} obj{$name($f)}
}

for n: $util_macos_mm $net_macos_mm
{
  obja{$(n).a.o}: mm{$n}
  objs{$(n).so.o}: mm{$n}
}

liba{util}: obja{$regex.apply($util_macos_mm,'(.+)','\1.a.o')}:  include = ($cxx.target.class == 'macos')
libs{util}: objs{$regex.apply($util_macos_mm,'(.+)','\1.so.o')}: include = ($cxx.target.class == 'macos')

liba{net}: obja{$regex.apply($net_macos_mm,'(.+)','\1.a.o')}:  include = ($cxx.target.class == 'macos')
libs{net}: objs{$regex.apply($net_macos_mm,'(.+)','\1.so.o')}: include = ($cxx.target.class == 'macos')

libul{meta}: $intf_libs

obja{~'/(.*).a/'}: mm{~'/\1/'} libua{meta}
{{
  lib_poptions = $cxx.lib_poptions(libua{meta}, obja)
  depdb hash $lib_poptions

  depdb dyndep "-I$out_base" "-I$src_base"                             \
              --what=header --default-type=h                           \
              --update-exclude libua{meta}                             \
              -- $cxx.path $cc.poptions $cxx.poptions $lib_poptions    \
              $cc.coptions $cxx.coptions $cxx.mode -M -MG $path($<[0])
  diag obj-c++ ($<[0])
  $cxx.path $cc.poptions $cxx.poptions $lib_poptions                    \
            $cc.coptions $cxx.coptions $cxx.mode                        \
            -o $path($>) -c -x objective-c++ $path($<[0])
}}

objs{~'/(.*).so/'}: mm{~'/\1/'} libus{meta}
{{
  lib_poptions = $cxx.lib_poptions(libus{meta}, objs)
  depdb hash $lib_poptions

  depdb dyndep "-I$out_base" "-I$src_base"                             \
              --what=header --default-type=h                           \
              --update-exclude libus{meta}                             \
              -- $cxx.path $cc.poptions $cxx.poptions $lib_poptions    \
              $cc.coptions $cxx.coptions $cxx.mode -M -MG $path($<[0])
  diag obj-c++ ($<[0])
  $cxx.path $cc.poptions $cxx.poptions $lib_poptions                    \
            $cc.coptions $cxx.coptions $cxx.mode                        \
            -o $path($>) -c -x objective-c++ $path($<[0])
}}

switch $cxx.target.class
{
  case 'macos'
    defs_files = mach/child_port.defs mach/notify.defs mach/exc.defs mach/mach_exc.defs
}

mig = /usr/bin/mig
xcrun = /usr/bin/xcrun
for def: $defs_files
{
  <{hxx}{mach/$name($def)} {cxx}{mach/"$name($def)"User} {hxx cxx}{mach/"$name($def)"Server}>: $mig $xcrun $def
  {{
    diag mig ($<[2])
    echo $path($<[2])
    mach_root = "$out_base"/mach
    $xcrun --show-sdk-path | set sdk_path
    defs_path = ($name($<[2]) == child_port ? "$src_root"/libcrashpad/util/mach : "$sdk_path"/usr/include/mach/)
    user_header_path = "$mach_root"/"$leaf($path($>[0]))"
    user_source_path = "$mach_root"/"$leaf($path($>[1]))"
    server_header_path = "$mach_root"/"$leaf($path($>[2]))"
    server_source_path = "$mach_root"/"$leaf($path($>[3]))"

    echo $path($<[2]) $user_header_path

    $mig -isysroot $sdk_path \
         "-I$src_root"/libcrashpad/ \
         "-I$src_root"/libcrashpad/compat/mac/ \
         -header $user_header_path \
         -user $user_source_path \
         -sheader $server_header_path \
         -server $server_source_path \
         "$defs_path"/"$leaf($path($<[2]))"

    #https://github.com/chromium/crashpad/blob/cca548be8467ce9d6e854467b366ad3a00c487ee/util/mach/mig_fix.py#L45-L49
    stub_replace = 's/^( \* (?:stub generated|with a MiG generated by) ).+$/\1<suppressed by mig_fix.py>/g'
    
    #https://github.com/chromium/crashpad/blob/cca548be8467ce9d6e854467b366ad3a00c487ee/util/mach/mig_fix.py#L72-L73
    reply_replace = 's/^(\t} __Reply);$/\1 __attribute__((unused));/g'

    #https://github.com/chromium/crashpad/blob/cca548be8467ce9d6e854467b366ad3a00c487ee/util/mach/mig_fix.py#L132
    mig_internal_replace = 's/^mig_internal (kern_return_t __MIG_check__.*)$/mig_external \1/g'

    #https://github.com/chromium/crashpad/blob/cca548be8467ce9d6e854467b366ad3a00c487ee/util/mach/mig_fix.py#L134-L141
    routine_replace = 's/OutP->RetCode = (([a-zA-Z0-9_]+)\(.+\));/OutP->RetCode = KERN_FAILURE; abort();/g'

    #https://github.com/chromium/crashpad/blob/cca548be8467ce9d6e854467b366ad3a00c487ee/util/mach/mig_fix.py#L114-L129
    cat $server_source_path | grep -E '^mig_internal (kern_return_t __MIG_check__.*)$' | sed -e 's/__attribute__\(\(__unused__\)\) //g' | sed -e 's/mig_internal //g' | sed -e 's/(.*)/\1;/' | sed -e 's/^/#ifdef mig_external
mig_external
#else
extern
#endif
/g' | set declarations

    # Fix user implementation
    sed -i -e $stub_replace $user_source_path
    #sed -i -e $reply_replace $user_source_path
    
    # Fix server implementation
    sed -i -e $stub_replace $server_source_path
    sed -i -e $mig_internal_replace $server_source_path
    sed -i -e $routine_replace $server_source_path
    # Have todo this 'hacky' solution because 'sed 1s' is not supported yet.
    echo '#include <stdlib.h>' | cat - $server_source_path > "$name($server_source_path)"_temp && mv "$name($server_source_path)"_temp $server_source_path

    # Fix user header
    echo '#ifdef __cplusplus
extern "C" {
#endif
' | cat - $user_header_path > "$name($user_header_path)"_temp && mv "$name($user_header_path)"_temp $user_header_path

    echo '

#ifdef __cplusplus
}
#endif' >> $user_header_path

    # Fix server header
    echo '#ifdef __cplusplus
extern "C" {
#endif
' | cat - $server_header_path > "$name($server_header_path)"_temp && mv "$name($server_header_path)"_temp $server_header_path

    echo $declarations >> $server_header_path
    echo '
#ifdef __cplusplus
}
#endif' >> $server_header_path
  }}

  lib{crashpad_util}: {hxx}{mach/$name($def)} {cxx}{mach/"$name($def)"User} {hxx cxx}{mach/"$name($def)"Server}
}

# Install into the crashpad/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/crashpad/util/
  install.subdirs = true
}
