import intf_libs += mini_chromium%lib{mini_chromium}

include ../build/
intf_libs += ../build/lib{crashpad_build}

./: lib{crashpad_tool_support}

lib{crashpad_tool_support}: {hxx}{tool_support ../package} {cxx}{tool_support} $intf_libs

# Build options.
cxx.poptions =+ "-I$src_root"/libcrashpad

# Export options.
lib{crashpad_tool_support}:
{
  cxx.export.poptions = "-I$src_root"/libcrashpad
  cxx.export.libs = $intf_libs
}

# Install into the crashpad/ subdirectory of, say, /usr/include/
# recreating subdirectories.
{hxx ixx txx}{*}:
{
  install         = include/crashpad/tools/
  install.subdirs = true
}

lib{crashpad_tool_support}: cxx.pkgconfig.include = include/crashpad/
